###
POST  http://localhost:3000/register
Content-Type: application/json

{
    "Name": "pepe",
    "Surname": "nico",
    "Age": 10,
    "Email": "nicd@gmail.com",
    "Pass":"niasaqwesdaqwesasddddc"

}




