###

GET  http://localhost:3000

{

}

###
GET  http://localhost:3000/Login


{
    
}

###
POST  http://localhost:3000/SendTask
Content-Type: application/json

{
    "Name": "f!",
    "Surname": "monkkey",
    "Age":"31"

}
###
POST  http://localhost:3000/SendUser
Content-Type: application/json

{
    "Name": "Nicolas",
    "Surname": "Lopez",
    "Age":"22",
    "Mail":"Fulano@gmail.com"
}